#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 017: Dependency Injection with Hilt

set -e

echo "========================================"
echo "Android Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Java version
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
    if [ "$JAVA_VERSION" -ge "17" ]; then
        echo -e "${GREEN}✓ Java $JAVA_VERSION detected${NC}"
    else
        echo -e "${RED}✗ Java 17+ required, found version $JAVA_VERSION${NC}"
        exit 1
    fi
else
    echo -e "${RED}✗ Java not found - please install JDK 17+${NC}"
    exit 1
fi

# Check Gradle wrapper
if [ -f "./gradlew" ]; then
    echo -e "${GREEN}✓ Gradle wrapper found${NC}"
else
    echo -e "${RED}✗ Gradle wrapper not found${NC}"
    exit 1
fi

# Check Android SDK (ANDROID_HOME)
if [ -z "$ANDROID_HOME" ]; then
    echo -e "${YELLOW}⚠ ANDROID_HOME not set - Android Studio may not be configured${NC}"
else
    echo -e "${GREEN}✓ ANDROID_HOME set to $ANDROID_HOME${NC}"
fi

# ============================================
# SETUP GRADLE DAEMON
# ============================================

echo ""
echo "Starting Gradle daemon..."
./gradlew --status || true

# ============================================
# VERIFY BUILD CONFIGURATION
# ============================================

echo ""
echo "Verifying build configuration..."
./gradlew :app:dependencies --configuration debugCompileClasspath > /dev/null 2>&1 && \
    echo -e "${GREEN}✓ Dependencies resolved${NC}" || \
    echo -e "${YELLOW}⚠ Warning: Unable to fully resolve dependencies${NC}"

# ============================================
# CHECK FOR CONNECTED DEVICES
# ============================================

echo ""
echo "Checking for connected Android devices/emulators..."
if command -v adb &> /dev/null; then
    DEVICES=$(adb devices | grep -v "List" | grep "device$" | wc -l)
    if [ "$DEVICES" -gt 0 ]; then
        echo -e "${GREEN}✓ Found $DEVICES connected device(s)${NC}"
        adb devices
    else
        echo -e "${YELLOW}⚠ No devices connected - you can connect one later${NC}"
    fi
else
    echo -e "${YELLOW}⚠ adb not found in PATH${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Task 017"
echo "========================================"
echo ""
echo "Task: Dependency Injection with Hilt"
echo "Workflow: SIMPLE (annotation additions + verification)"
echo ""
echo "Next Steps:"
echo "1. Run coder agent to implement subtasks:"
echo "   source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 017 --parallel 1"
echo ""
echo "2. Or manually build the project:"
echo "   ./gradlew clean assembleDebug"
echo ""
echo "3. Connect an Android device or start an emulator:"
echo "   - Physical device: Enable USB debugging and connect via USB"
echo "   - Emulator: Launch from Android Studio (Tools → AVD Manager)"
echo ""
echo "4. Install and run the app:"
echo "   ./gradlew installDebug"
echo ""
echo "Files to be modified/created:"
echo "  - app/src/main/java/com/inventory/app/MainActivity.kt (add @AndroidEntryPoint)"
echo "  - app/src/main/java/com/inventory/ui/MainViewModel.kt (create new)"
echo ""
