#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 004: Set up dependency injection framework

set -e

echo "========================================"
echo "Android DI Setup - Environment Check"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check Java/JDK
echo "Checking Java installation..."
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo -e "${GREEN}Java found: $JAVA_VERSION${NC}"
else
    echo -e "${RED}Java not found! Please install JDK 11 or higher${NC}"
    exit 1
fi

# Check Android SDK (optional, warn if not found)
echo "Checking Android SDK..."
if [ -z "$ANDROID_HOME" ] && [ -z "$ANDROID_SDK_ROOT" ]; then
    echo -e "${YELLOW}Warning: ANDROID_HOME not set. Android Studio is recommended for building.${NC}"
    echo -e "${YELLOW}Continuing anyway - Gradle may download SDK components${NC}"
else
    echo -e "${GREEN}Android SDK found${NC}"
fi

# Create Gradle wrapper if it doesn't exist
echo "Setting up Gradle wrapper..."
if [ ! -f "./gradlew" ]; then
    echo -e "${YELLOW}Gradle wrapper not found. It will be created during first build.${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Check Complete!"
echo "========================================"
echo ""
echo "Project: Inventory APK - Hilt DI Setup"
echo "Type: Android Application"
echo "Build Tool: Gradle"
echo ""
echo "Next Steps:"
echo "  1. Implement the project structure (Phase 1)"
echo "  2. Build with: ./gradlew clean app:assembleDebug"
echo "  3. Or open in Android Studio for GUI development"
echo ""
echo "For parallel execution:"
echo "  source auto-claude/.venv/bin/activate"
echo "  python auto-claude/run.py --spec 004 --parallel 1"
echo ""
