#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 006
# Project: inventory-apk - README.md Verification

set -e

echo "========================================"
echo "Documentation Verification Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${GREEN}Project Type:${NC} Documentation-only (greenfield)"
echo -e "${GREEN}Task:${NC} Verify README.md completeness"
echo ""

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo "Checking environment..."

# Check if README.md exists
if [ -f "README.md" ]; then
    echo -e "${GREEN}✓${NC} README.md found"
    echo "  Lines: $(wc -l < README.md)"
    echo "  Size: $(du -h README.md | cut -f1)"
else
    echo -e "${RED}✗${NC} README.md not found"
    exit 1
fi

# Check for optional markdown linter
if command -v markdownlint >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} markdownlint available"
else
    echo -e "${YELLOW}ℹ${NC} markdownlint not installed (optional)"
    echo "  Install with: npm install -g markdownlint-cli"
fi

# Check for grep (should always be available)
if command -v grep >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} grep available"
else
    echo -e "${RED}✗${NC} grep not found"
    exit 1
fi

# ============================================
# NO SERVICES TO START
# ============================================

echo ""
echo -e "${YELLOW}Note:${NC} This is a documentation verification task."
echo "No services need to be started."
echo ""

# ============================================
# SUMMARY
# ============================================

echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Task: Verify README.md completeness"
echo ""
echo "Next steps:"
echo "  1. Review README.md for required sections"
echo "  2. Verify project overview is present"
echo "  3. Verify goals/purpose are explained"
echo "  4. Verify quick start guide exists"
echo "  5. Validate markdown formatting"
echo ""
echo "README sections to verify:"
echo "  • 📋 Overview"
echo "  • 🎯 Purpose"
echo "  • ✨ Key Features"
echo "  • 🚀 Getting Started"
echo "  • 📚 Documentation"
echo "  • 🛠️ Technology Stack"
echo ""
echo -e "${GREEN}Ready to proceed with verification!${NC}"
echo ""
