#!/bin/bash

# Auto-Build Environment Setup for NewlandScannerManager
# Generated by Planner Agent

set -e

echo "========================================"
echo "Android Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Java/JDK
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo -e "${GREEN}✓${NC} Java found: $JAVA_VERSION"
else
    echo -e "${RED}✗${NC} Java not found. Please install JDK 11 or higher."
    exit 1
fi

# Check Android SDK
if [ -z "$ANDROID_HOME" ] && [ -z "$ANDROID_SDK_ROOT" ]; then
    echo -e "${YELLOW}⚠${NC} ANDROID_HOME not set. Please configure Android SDK."
    echo "  Set ANDROID_HOME environment variable to your Android SDK location"
else
    echo -e "${GREEN}✓${NC} Android SDK configured: ${ANDROID_HOME:-$ANDROID_SDK_ROOT}"
fi

# Check Gradle wrapper (will be created in subtask-1-1)
if [ -f "./gradlew" ]; then
    GRADLE_VERSION=$(./gradlew --version | grep "Gradle" | awk '{print $2}')
    echo -e "${GREEN}✓${NC} Gradle wrapper found: $GRADLE_VERSION"
else
    echo -e "${YELLOW}⚠${NC} Gradle wrapper not found. Will be created during project setup."
fi

# ============================================
# PROJECT STRUCTURE
# ============================================

echo ""
echo "Project Information:"
echo "  Type:        Android Application"
echo "  Language:    Kotlin"
echo "  Min SDK:     API 24 (Android 7.0)"
echo "  Target:      Newland MT90 device"
echo "  DI:          Hilt"
echo "  UI:          Jetpack Compose"
echo ""

# ============================================
# GRADLE SYNC (if project exists)
# ============================================

if [ -f "./gradlew" ]; then
    echo "Syncing Gradle dependencies..."
    ./gradlew --refresh-dependencies || echo -e "${YELLOW}Gradle sync failed - may need manual sync in Android Studio${NC}"
else
    echo "Gradle project not yet created. Run phase-1 subtasks first."
fi

# ============================================
# INSTRUCTIONS
# ============================================

echo ""
echo "========================================"
echo "Next Steps"
echo "========================================"
echo ""
echo "1. Run the auto-claude coder agent:"
echo "   ${GREEN}source auto-claude/.venv/bin/activate${NC}"
echo "   ${GREEN}python auto-claude/run.py --spec 019 --parallel 1${NC}"
echo ""
echo "2. After coder completes project setup, open in Android Studio:"
echo "   - File → Open → Select this directory"
echo "   - Wait for Gradle sync to complete"
echo "   - Connect MT90 device via USB"
echo "   - Enable USB debugging on device"
echo "   - Click Run button"
echo ""
echo "3. For manual testing on MT90:"
echo "   - Install APK: ./gradlew installDebug"
echo "   - View logs: adb logcat | grep Scanner"
echo "   - Test hardware button: Press F6 key"
echo ""
echo "========================================"
echo "Environment Check Complete"
echo "========================================"
