#!/bin/bash

# Auto-Build Environment Setup
# Task: Configure CI pipeline with build and lint checks
# Generated by Planner Agent

set -e

echo "========================================"
echo "CI/CD Pipeline Setup - Task 003"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "Project: inventory-apk (Android)"
echo "Task: Add GitHub Actions workflow for CI/CD"
echo ""

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo "Verifying project structure..."

# Check if we're in the right directory
if [ ! -f ".gitignore" ]; then
    echo -e "${RED}Error: Not in project root directory${NC}"
    exit 1
fi

echo -e "${GREEN}Project root verified${NC}"

# ============================================
# CHECK GRADLE WRAPPER (from task 001)
# ============================================

echo ""
echo "Checking for Gradle wrapper..."

if [ -f "gradlew" ]; then
    echo -e "${GREEN}Gradle wrapper found${NC}"
    echo "  - gradlew: $(./gradlew --version 2>/dev/null | head -3 | tail -1 || echo 'Ready')"
else
    echo -e "${YELLOW}Note: Gradle wrapper not found yet${NC}"
    echo "  - Will be created by task 001 (project scaffolding)"
fi

# ============================================
# PREPARE CI/CD DIRECTORY
# ============================================

echo ""
echo "Preparing GitHub Actions directory..."

if [ ! -d ".github" ]; then
    echo "  - .github/ directory will be created"
fi

if [ ! -d ".github/workflows" ]; then
    echo "  - .github/workflows/ directory will be created"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Check Complete"
echo "========================================"
echo ""
echo "Ready to create:"
echo "  - .github/workflows/android-ci.yml"
echo ""
echo "The workflow will include:"
echo "  1. Build job: ./gradlew assembleDebug"
echo "  2. Lint job: ./gradlew lint"
echo "  3. Test job: ./gradlew test"
echo ""
echo "Triggers:"
echo "  - On push to main branch"
echo "  - On all pull requests"
echo ""
echo -e "${GREEN}Setup verification complete!${NC}"
echo ""
