#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Android Project Scaffolding

set -e

echo "========================================"
echo "Android Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Java
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2)
    echo -e "${GREEN}✓ Java found: $JAVA_VERSION${NC}"
else
    echo -e "${RED}✗ Java not found. Please install JDK 17 or higher.${NC}"
    exit 1
fi

# Check Android SDK
if [ -z "$ANDROID_HOME" ]; then
    echo -e "${YELLOW}⚠ ANDROID_HOME not set${NC}"
    echo "Please set ANDROID_HOME to your Android SDK location"
    echo "Example: export ANDROID_HOME=/Users/yourusername/Library/Android/sdk"

    # Common Android SDK locations
    COMMON_LOCATIONS=(
        "$HOME/Library/Android/sdk"
        "$HOME/Android/Sdk"
        "/usr/local/android-sdk"
        "C:/Users/$USER/AppData/Local/Android/Sdk"
    )

    for loc in "${COMMON_LOCATIONS[@]}"; do
        if [ -d "$loc" ]; then
            echo -e "${YELLOW}Found SDK at: $loc${NC}"
            echo "Run: export ANDROID_HOME=$loc"
            break
        fi
    done
else
    echo -e "${GREEN}✓ ANDROID_HOME: $ANDROID_HOME${NC}"
fi

# Check Gradle
if [ -f "./gradlew" ]; then
    chmod +x ./gradlew
    echo -e "${GREEN}✓ Gradle wrapper found and made executable${NC}"
else
    echo -e "${YELLOW}⚠ Gradle wrapper not yet created (will be created during scaffolding)${NC}"
fi

# ============================================
# PROJECT STRUCTURE
# ============================================

echo ""
echo "Current project structure:"
if [ -d "./app" ]; then
    echo -e "${GREEN}✓ app/ directory exists${NC}"
    if [ -f "./app/build.gradle.kts" ]; then
        echo -e "${GREEN}✓ app/build.gradle.kts exists${NC}"
    fi
    if [ -f "./app/src/main/AndroidManifest.xml" ]; then
        echo -e "${GREEN}✓ AndroidManifest.xml exists${NC}"
    fi
else
    echo -e "${YELLOW}⚠ app/ directory not yet created${NC}"
fi

# ============================================
# GRADLE SYNC (if project exists)
# ============================================

if [ -f "./gradlew" ] && [ -f "./settings.gradle.kts" ]; then
    echo ""
    echo "Running Gradle sync..."
    ./gradlew tasks --quiet > /dev/null 2>&1 || echo -e "${YELLOW}⚠ Gradle sync incomplete (this is expected for new projects)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Status"
echo "========================================"
echo ""
echo "Development Environment:"
echo "  Java:         $(command -v java &> /dev/null && echo 'Installed' || echo 'Not found')"
echo "  Android SDK:  $([ -n "$ANDROID_HOME" ] && echo 'Configured' || echo 'Not configured')"
echo "  Gradle:       $([ -f "./gradlew" ] && echo 'Ready' || echo 'Pending')"
echo ""
echo "Project Status:"
echo "  Structure:    $([ -d "./app" ] && echo 'Exists' || echo 'Not created')"
echo "  Manifest:     $([ -f "./app/src/main/AndroidManifest.xml" ] && echo 'Exists' || echo 'Not created')"
echo "  Build Files:  $([ -f "./build.gradle.kts" ] && echo 'Exists' || echo 'Not created')"
echo ""

if [ -f "./gradlew" ] && [ -f "./app/build.gradle.kts" ]; then
    echo "Common commands:"
    echo "  ./gradlew tasks           - List all tasks"
    echo "  ./gradlew assembleDebug   - Build debug APK"
    echo "  ./gradlew installDebug    - Install on device/emulator"
    echo "  ./gradlew clean           - Clean build artifacts"
    echo ""
fi

echo "Ready for implementation!"
echo "========================================"
