#!/bin/bash

# Android Project Setup Script
# Generated by Planner Agent for Spec 016

set -e

echo "========================================"
echo "Android Project Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PREREQUISITE CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Java/JDK
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
    if [ "$JAVA_VERSION" -ge 11 ]; then
        echo -e "${GREEN}✓${NC} Java $JAVA_VERSION detected"
    else
        echo -e "${RED}✗${NC} Java 11 or higher required (found Java $JAVA_VERSION)"
        echo "  Install JDK 11+ from: https://adoptium.net/"
        exit 1
    fi
else
    echo -e "${RED}✗${NC} Java not found"
    echo "  Install JDK 11+ from: https://adoptium.net/"
    exit 1
fi

# Check Android SDK (via ANDROID_HOME or ANDROID_SDK_ROOT)
if [ -n "$ANDROID_HOME" ] || [ -n "$ANDROID_SDK_ROOT" ]; then
    echo -e "${GREEN}✓${NC} Android SDK found"
else
    echo -e "${YELLOW}⚠${NC}  ANDROID_HOME not set"
    echo "  Android Studio will set this automatically"
    echo "  Or set manually: export ANDROID_HOME=/path/to/sdk"
fi

# ============================================
# PROJECT SETUP
# ============================================

echo ""
echo "Setting up project..."

# Make gradlew executable (will exist after implementation)
if [ -f "./gradlew" ]; then
    chmod +x ./gradlew
    echo -e "${GREEN}✓${NC} Gradle wrapper executable"
else
    echo -e "${YELLOW}⚠${NC}  gradlew not found (will be created during implementation)"
fi

# ============================================
# BUILD VERIFICATION
# ============================================

echo ""
echo "Verifying build setup..."

if [ -f "./gradlew" ] && [ -f "./app/build.gradle.kts" ]; then
    echo "Running Gradle sync..."
    ./gradlew tasks --dry-run
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓${NC} Gradle sync successful"
    else
        echo -e "${RED}✗${NC} Gradle sync failed"
        exit 1
    fi
else
    echo -e "${YELLOW}⚠${NC}  Project files not yet created - skip build verification"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Open project in Android Studio"
echo "  2. Wait for Gradle sync to complete"
echo "  3. Connect Android device or start emulator"
echo "  4. Run: ./gradlew installDebug"
echo ""
echo "Target Device: Newland MT90 (Android 10/11)"
echo "Min SDK: 29 | Target SDK: 34 | Compile SDK: 34"
echo ""
echo "Development Commands:"
echo "  ./gradlew assembleDebug       - Build debug APK"
echo "  ./gradlew assembleRelease     - Build release APK"
echo "  ./gradlew installDebug        - Install on device"
echo "  ./gradlew test                - Run unit tests"
echo "  ./gradlew clean               - Clean build artifacts"
echo ""
